title: ColinG.uk/blog
description: Colin's Blog

url: https://coling.uk
baseurl: "/blog/"
paginate_path: "page:num/"
permalink: :title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html

social:
  github: -
  twitter: -
  facebook: -
  email: -

google_analytics: ""
