title: ColinG.uk/blog
description: Colin's Blog

url: https://coling.uk
baseurl: "/blog/"
paginate_path: "page:num/"
permalink: :title/

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
remote_theme: benbalter/retlab

markdown: kramdown
highlighter: rouge
paginate: 5

navigation:
  - title: Home
    url: /index.html

social:
  github: -
  twitter: -
  facebook: -
  email: -

google_analytics: ""
